# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/about.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from utils.resources import Resources


class Ui_AboutWindow(object):
    def setupUi(self, AboutWindow):
        AboutWindow.setObjectName("AboutWindow")
        AboutWindow.resize(687, 227)
        self.centralwidget = QtWidgets.QWidget(AboutWindow)

        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(Resources.getQPixmapByFilename('app.ico')))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.appNameLabel = QtWidgets.QLabel(self.frame_2)

        self.appNameLabel.setObjectName("appNameLabel")
        self.verticalLayout.addWidget(self.appNameLabel)
        self.versionLabel = QtWidgets.QLabel(self.frame_2)
        self.versionLabel.setStyleSheet("margin-bottom:14px")
        self.versionLabel.setObjectName("versionLabel")
        self.verticalLayout.addWidget(self.versionLabel)
        self.horizontalLayout_3.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.checkUpdatepushButton = QtWidgets.QPushButton(self.frame)

        self.checkUpdatepushButton.setObjectName("checkUpdatepushButton")
        self.horizontalLayout_3.addWidget(self.checkUpdatepushButton)
        self.verticalLayout_2.addWidget(self.frame)
        self.descriptionLabel = QtWidgets.QLabel(self.centralwidget)
        self.descriptionLabel.setToolTip("")
        self.descriptionLabel.setTextFormat(QtCore.Qt.AutoText)
        self.descriptionLabel.setWordWrap(True)
        self.descriptionLabel.setOpenExternalLinks(True)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout_2.addWidget(self.descriptionLabel)
        self.copyrightLabel = QtWidgets.QLabel(self.centralwidget)
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.verticalLayout_2.addWidget(self.copyrightLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        AboutWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AboutWindow)
        QtCore.QMetaObject.connectSlotsByName(AboutWindow)

    def retranslateUi(self, AboutWindow):
        pros = AboutWindow.app.strings.properties
        _translate = QtCore.QCoreApplication.translate
        AboutWindow.setWindowTitle(_translate("AboutWindow", pros['about.windowsTitle']))
        self.appNameLabel.setText(_translate("AboutWindow", pros['about.appName']))
        self.versionLabel.setText(_translate("AboutWindow", pros['about.version']))
        self.checkUpdatepushButton.setText(_translate("AboutWindow", pros['about.checkUpdate']))
        self.descriptionLabel.setText(_translate("AboutWindow", pros['about.description']))
        self.copyrightLabel.setText(_translate("AboutWindow", pros['about.copyright']))

