# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/edit_server.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from utils.resources import Resources


class Ui_EditServerWindow(object):
    def setupUi(self, EditServerWindow):
        EditServerWindow.setObjectName("EditServerWindow")
        EditServerWindow.resize(1084, 1008)
        EditServerWindow.setStyleSheet("QComboBox {\n"
"    width: 100px;\n"
"    cursor: pointer;\n"
"    margin: 0;\n"
"    box-sizing: border-box;\n"
"    transition: all 0.2s ease-in-out;\n"
"    font-family: inherit;\n"
"    height: 32px;\n"
"    font-size: 16px;\n"
"    line-height: 20px;\n"
"    font-weight: 400;\n"
"    background: #FFFFFF;\n"
"    border: 1px solid #B6B6B6;\n"
"    color: #262626;\n"
"    padding: 0 11px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    width: 100px;\n"
"    cursor: pointer;\n"
"    margin: 0;\n"
"    box-sizing: border-box;\n"
"    transition: all 0.2s ease-in-out;\n"
"    font-family: inherit;\n"
"    height: 32px;\n"
"    font-size: 16px;\n"
"    line-height: 20px;\n"
"    font-weight: 400;\n"
"    background:#FFFFFF;\n"
"    border: 1px solid #B6B6B6;\n"
"    color: #262626;\n"
"    padding: 0 11px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol- position :  top  right ;\n"
"     width :  20px ;\n"
"     font-size: 16px;\n"
"      border:none;\n"
"}\n"
" \n"
"QComboBox::down-arrow {\n"
"    margin-right:10px;\n"
"    image: url("+ Resources.getResourcesPath('keyboard_arrow_down_16dp.png').replace('\\', '/') +");\n"
"}\n"
"\n"
"QPushButton{\n"
"    cursor: pointer;\n"
"    display: inline-flex;\n"
"    overflow: hidden;\n"
"    max-width: 374px;\n"
"    box-sizing: border-box;\n"
"    transition: all 0.1s ease-in-out;\n"
"    line-height: 1;\n"
"    font-family: inherit;\n"
"    align-items: center;\n"
"    white-space: nowrap;\n"
"    justify-content: center;\n"
"    text-decoration: none;\n"
"    font-size: 16px;\n"
"    min-width: 32px;\n"
"    padding: 0 8px;\n"
"    height: 32px;\n"
"    border: 1px solid #B6B6B6;\n"
"    border-radius: 2px;\n"
"    color: #262626;\n"
"    background-color: rgb(229, 229, 229);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
" \n"
"QPushButton:pressed{\n"
"    background-color: rgb(144, 144, 144);\n"
"}\n"
"QPushButton:!enabled{\n"
"    background-color: rgb(100, 100, 100);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"QGroupBox {\n"
"   \n"
"    border: 1px solid #B6B6B6;\n"
"    border-radius: 5px;\n"
"    margin-top: 6px;\n"
"}\n"
"\n"
"/* 标题设置 */\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    left:10px;\n"
"    margin-left: 0px;\n"
"    padding:0 1px;\n"
"    \n"
"}\n"
"\n"
"QListWidget{\n"
"    border:none;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    font: 14px \"Segoe UI\";\n"
"}\n"
"\n"
"QListWidget::item{\n"
"    padding:8px 2px;\n"
"    color:rgb(0, 0, 0);\n"
"       /*margin-left:40px;*/\n"
"}\n"
"QListWidget::item:hover{\n"
"    background-color:rgb(208, 208, 208);\n"
"    /*border-bottom:1px solid rgb(121,112,52);*/\n"
"}\n"
"QListWidget::item:selected\n"
"{\n"
"    \n"
"    background-color: rgb(199, 199, 199);\n"
"   /* border-bottom:1px solid rgb(121,112,52);\n"
"    padding:0px;\n"
"    margin:0px;\n"
"    color:red;*/\n"
"}\n"
"QListWidget::item:selected:!active\n"
"{\n"
"    border-width:0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(EditServerWindow)
        self.centralwidget.setStyleSheet("QMainWindow{\n"
"  background-color: rgb(247, 247, 247);\n"
"}\n"
"QWudget{\n"
"    background-color: rgb(247, 247, 247);\n"
"    font-family: \"system-ui\", sans-serif;\n"
"    font-size: 16px;\n"
"}\n"
"QFrame{\n"
"    background-color: rgb(247, 247, 247);\n"
"    font-family: \"system-ui\", sans-serif;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_13 = QtWidgets.QFrame(self.frame_9)
        self.frame_13.setMaximumSize(QtCore.QSize(270, 16777215))
        self.frame_13.setStyleSheet("")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setContentsMargins(11, 11, 0, 11)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.listWidget = QtWidgets.QListWidget(self.frame_13)
        self.listWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.listWidget.setStyleSheet("QListWidget{\n"
"     border: 1px solid #B6B6B6;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_6.addWidget(self.listWidget)
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setStyleSheet("QPushButton{\n"
"    border-radius: 0;\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout.setContentsMargins(0, 5, 14, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addPushButton = QtWidgets.QPushButton(self.frame_14)
        self.addPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(Resources.getQPixmapByFilename("baseline_add_black_18dp.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.addPushButton.setIcon(icon1)
        self.addPushButton.setObjectName("addPushButton")
        self.horizontalLayout.addWidget(self.addPushButton)
        self.addFromLinkPushButton = QtWidgets.QPushButton(self.frame_14)
        self.addFromLinkPushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(Resources.getQPixmapByFilename("baseline_add_link_black_18dp.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.addFromLinkPushButton.setIcon(icon2)
        self.addFromLinkPushButton.setObjectName("addFromLinkPushButton")
        self.horizontalLayout.addWidget(self.addFromLinkPushButton)
        self.deletePushButton = QtWidgets.QPushButton(self.frame_14)
        self.deletePushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(Resources.getQPixmapByFilename("baseline_delete_black_18dp.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.deletePushButton.setIcon(icon3)
        self.deletePushButton.setObjectName("deletePushButton")
        self.horizontalLayout.addWidget(self.deletePushButton)
        self.showQRCodePushButton = QtWidgets.QPushButton(self.frame_14)
        self.showQRCodePushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(Resources.getQPixmapByFilename("baseline_qr_code_2_black_18dp.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.showQRCodePushButton.setIcon(icon4)
        self.showQRCodePushButton.setObjectName("showQRCodePushButton")
        self.horizontalLayout.addWidget(self.showQRCodePushButton)
        self.sharPushButton = QtWidgets.QPushButton(self.frame_14)
        self.sharPushButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(Resources.getQPixmapByFilename("baseline_share_black_18dp.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.sharPushButton.setIcon(icon5)
        self.sharPushButton.setObjectName("sharPushButton")
        self.horizontalLayout.addWidget(self.sharPushButton)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.horizontalLayout_12.addWidget(self.frame_13)
        self.frame = QtWidgets.QFrame(self.frame_9)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outBoundGroupBox = QtWidgets.QGroupBox(self.frame)
        self.outBoundGroupBox.setObjectName("outBoundGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.outBoundGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.outBoundGroupBox)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.protocolLabel = QtWidgets.QLabel(self.frame_11)
        self.protocolLabel.setObjectName("protocolLabel")
        self.horizontalLayout_11.addWidget(self.protocolLabel)
        self.protocolComboBox = QtWidgets.QComboBox(self.frame_11)
        self.protocolComboBox.setObjectName("protocolComboBox")
        self.protocolComboBox.addItem("")
        self.protocolComboBox.addItem("")
        self.protocolComboBox.addItem("")
        self.protocolComboBox.addItem("")
        self.protocolComboBox.addItem("")
        self.horizontalLayout_11.addWidget(self.protocolComboBox)
        self.remakeLabel = QtWidgets.QLabel(self.frame_11)
        self.remakeLabel.setObjectName("remakeLabel")
        self.horizontalLayout_11.addWidget(self.remakeLabel)
        self.remakeLineEdit = QtWidgets.QLineEdit(self.frame_11)
        self.remakeLineEdit.setObjectName("remakeLineEdit")
        self.horizontalLayout_11.addWidget(self.remakeLineEdit)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.verticalLayout.addWidget(self.outBoundGroupBox)
        self.serverGroupBox = QtWidgets.QGroupBox(self.frame)
        self.serverGroupBox.setObjectName("serverGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.serverGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.serverGroupBox)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addressLabel = QtWidgets.QLabel(self.frame_2)
        self.addressLabel.setObjectName("addressLabel")
        self.horizontalLayout_2.addWidget(self.addressLabel)
        self.addressLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.horizontalLayout_2.addWidget(self.addressLineEdit)
        self.portLabel = QtWidgets.QLabel(self.frame_2)
        self.portLabel.setObjectName("portLabel")
        self.horizontalLayout_2.addWidget(self.portLabel)
        self.portLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.portLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.portLineEdit.setObjectName("portLineEdit")
        self.horizontalLayout_2.addWidget(self.portLineEdit)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_17 = QtWidgets.QFrame(self.serverGroupBox)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.UUIDLabel = QtWidgets.QLabel(self.frame_17)
        self.UUIDLabel.setObjectName("UUIDLabel")
        self.horizontalLayout_15.addWidget(self.UUIDLabel)
        self.UUIDLineEdit = QtWidgets.QLineEdit(self.frame_17)
        self.UUIDLineEdit.setObjectName("UUIDLineEdit")
        self.horizontalLayout_15.addWidget(self.UUIDLineEdit)
        self.verticalLayout_2.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.serverGroupBox)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.alterIdLabel = QtWidgets.QLabel(self.frame_18)
        self.alterIdLabel.setObjectName("alterIdLabel")
        self.horizontalLayout_16.addWidget(self.alterIdLabel)
        self.alterIdLineEdit = QtWidgets.QLineEdit(self.frame_18)
        self.alterIdLineEdit.setObjectName("alterIdLineEdit")
        self.horizontalLayout_16.addWidget(self.alterIdLineEdit)
        self.flowLabel = QtWidgets.QLabel(self.frame_18)
        self.flowLabel.setObjectName("flowLabel")
        self.horizontalLayout_16.addWidget(self.flowLabel)
        self.flowComboBox = QtWidgets.QComboBox(self.frame_18)
        self.flowComboBox.setObjectName("flowComboBox")
        self.flowComboBox.addItem("")
        self.horizontalLayout_16.addWidget(self.flowComboBox)
        self.securityLabel_2 = QtWidgets.QLabel(self.frame_18)
        self.securityLabel_2.setObjectName("securityLabel_2")
        self.horizontalLayout_16.addWidget(self.securityLabel_2)
        self.securityComboBox_2 = QtWidgets.QComboBox(self.frame_18)
        self.securityComboBox_2.setObjectName("securityComboBox_2")
        self.securityComboBox_2.addItem("")
        self.securityComboBox_2.addItem("")
        self.securityComboBox_2.addItem("")
        self.securityComboBox_2.addItem("")
        self.securityComboBox_2.addItem("")
        self.horizontalLayout_16.addWidget(self.securityComboBox_2)
        self.levelLabel = QtWidgets.QLabel(self.frame_18)
        self.levelLabel.setObjectName("levelLabel")
        self.horizontalLayout_16.addWidget(self.levelLabel)
        self.levelLineEdit = QtWidgets.QLineEdit(self.frame_18)
        self.levelLineEdit.setObjectName("levelLineEdit")
        self.horizontalLayout_16.addWidget(self.levelLineEdit)
        self.verticalLayout_2.addWidget(self.frame_18)
        self.frame_16 = QtWidgets.QFrame(self.serverGroupBox)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.userLabel = QtWidgets.QLabel(self.frame_16)
        self.userLabel.setObjectName("userLabel")
        self.horizontalLayout_14.addWidget(self.userLabel)
        self.userLineEdit = QtWidgets.QLineEdit(self.frame_16)
        self.userLineEdit.setObjectName("userLineEdit")
        self.horizontalLayout_14.addWidget(self.userLineEdit)
        self.verticalLayout_2.addWidget(self.frame_16)
        self.frame_3 = QtWidgets.QFrame(self.serverGroupBox)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.passwordLabel = QtWidgets.QLabel(self.frame_3)
        self.passwordLabel.setObjectName("passwordLabel")
        self.horizontalLayout_3.addWidget(self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.horizontalLayout_3.addWidget(self.passwordLineEdit)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.serverGroupBox)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.methodLabel = QtWidgets.QLabel(self.frame_4)
        self.methodLabel.setObjectName("methodLabel")
        self.horizontalLayout_4.addWidget(self.methodLabel)
        self.methodComboBox = QtWidgets.QComboBox(self.frame_4)
        self.methodComboBox.setObjectName("methodComboBox")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.methodComboBox)
        self.otaLabel = QtWidgets.QLabel(self.frame_4)
        self.otaLabel.setObjectName("otaLabel")
        self.horizontalLayout_4.addWidget(self.otaLabel)
        self.otaComboBox = QtWidgets.QComboBox(self.frame_4)
        self.otaComboBox.setObjectName("otaComboBox")
        self.otaComboBox.addItem("")
        self.otaComboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.otaComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.serverGroupBox)
        self.streamGroupBox = QtWidgets.QGroupBox(self.frame)
        self.streamGroupBox.setObjectName("streamGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.streamGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.streamGroupBox)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.networkLabel = QtWidgets.QLabel(self.frame_5)
        self.networkLabel.setObjectName("networkLabel")
        self.horizontalLayout_5.addWidget(self.networkLabel)
        self.networkComboBox = QtWidgets.QComboBox(self.frame_5)
        self.networkComboBox.setObjectName("networkComboBox")
        self.networkComboBox.addItem("")
        self.networkComboBox.addItem("")
        self.networkComboBox.addItem("")
        self.networkComboBox.addItem("")
        self.networkComboBox.addItem("")
        self.networkComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.networkComboBox)
        self.securityLabel = QtWidgets.QLabel(self.frame_5)
        self.securityLabel.setObjectName("securityLabel")
        self.horizontalLayout_5.addWidget(self.securityLabel)
        self.securityComboBox = QtWidgets.QComboBox(self.frame_5)
        self.securityComboBox.setObjectName("securityComboBox")
        self.securityComboBox.addItem("")
        self.securityComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.securityComboBox)
        self.dsrLabel = QtWidgets.QLabel(self.frame_5)
        self.dsrLabel.setObjectName("dsrLabel")
        self.horizontalLayout_5.addWidget(self.dsrLabel)
        self.dsrComboBox = QtWidgets.QComboBox(self.frame_5)
        self.dsrComboBox.setObjectName("dsrComboBox")
        self.dsrComboBox.addItem("")
        self.dsrComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.dsrComboBox)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.streamGroupBox)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.serverNameLabel = QtWidgets.QLabel(self.frame_7)
        self.serverNameLabel.setObjectName("serverNameLabel")
        self.horizontalLayout_6.addWidget(self.serverNameLabel)
        self.serverNameLineEdit = QtWidgets.QLineEdit(self.frame_7)
        self.serverNameLineEdit.setObjectName("serverNameLineEdit")
        self.horizontalLayout_6.addWidget(self.serverNameLineEdit)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.streamGroupBox)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.allowInsecureLabel = QtWidgets.QLabel(self.frame_6)
        self.allowInsecureLabel.setObjectName("allowInsecureLabel")
        self.horizontalLayout_7.addWidget(self.allowInsecureLabel)
        self.allowInsecureComboBox = QtWidgets.QComboBox(self.frame_6)
        self.allowInsecureComboBox.setObjectName("allowInsecureComboBox")
        self.allowInsecureComboBox.addItem("")
        self.allowInsecureComboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.allowInsecureComboBox)
        self.alpnLabel = QtWidgets.QLabel(self.frame_6)
        self.alpnLabel.setObjectName("alpnLabel")
        self.horizontalLayout_7.addWidget(self.alpnLabel)
        self.alpnLineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.alpnLineEdit.setObjectName("alpnLineEdit")
        self.horizontalLayout_7.addWidget(self.alpnLineEdit)
        self.usageLabel = QtWidgets.QLabel(self.frame_6)
        self.usageLabel.setObjectName("usageLabel")
        self.horizontalLayout_7.addWidget(self.usageLabel)
        self.usageComboBox = QtWidgets.QComboBox(self.frame_6)
        self.usageComboBox.setObjectName("usageComboBox")
        self.usageComboBox.addItem("")
        self.usageComboBox.addItem("")
        self.usageComboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.usageComboBox)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.streamGroupBox)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cerLabel = QtWidgets.QLabel(self.frame_8)
        self.cerLabel.setObjectName("cerLabel")
        self.horizontalLayout_8.addWidget(self.cerLabel)
        self.cerFilePathLineEdit = QtWidgets.QLineEdit(self.frame_8)
        self.cerFilePathLineEdit.setEnabled(False)
        self.cerFilePathLineEdit.setObjectName("cerFilePathLineEdit")
        self.horizontalLayout_8.addWidget(self.cerFilePathLineEdit)
        self.chooseCerFilePushButton = QtWidgets.QPushButton(self.frame_8)
        self.chooseCerFilePushButton.setObjectName("chooseCerFilePushButton")
        self.horizontalLayout_8.addWidget(self.chooseCerFilePushButton)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.streamGroupBox)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.keyLabel = QtWidgets.QLabel(self.frame_10)
        self.keyLabel.setObjectName("keyLabel")
        self.horizontalLayout_9.addWidget(self.keyLabel)
        self.chooseKeyFileLineEdit = QtWidgets.QLineEdit(self.frame_10)
        self.chooseKeyFileLineEdit.setEnabled(False)
        self.chooseKeyFileLineEdit.setObjectName("chooseKeyFileLineEdit")
        self.horizontalLayout_9.addWidget(self.chooseKeyFileLineEdit)
        self.chooseKeyFilePushButton = QtWidgets.QPushButton(self.frame_10)
        self.chooseKeyFilePushButton.setObjectName("chooseKeyFilePushButton")
        self.horizontalLayout_9.addWidget(self.chooseKeyFilePushButton)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_12 = QtWidgets.QFrame(self.streamGroupBox)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.advancedPushButton = QtWidgets.QPushButton(self.frame_12)
        self.advancedPushButton.setObjectName("advancedPushButton")
        self.horizontalLayout_10.addWidget(self.advancedPushButton)
        self.verticalLayout_3.addWidget(self.frame_12)
        self.verticalLayout.addWidget(self.streamGroupBox)
        self.horizontalLayout_12.addWidget(self.frame)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setStyleSheet("QPushButton{\n"
"    width:100px;\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.resetPushButton = QtWidgets.QPushButton(self.frame_15)
        self.resetPushButton.setMinimumSize(QtCore.QSize(118, 0))
        self.resetPushButton.setMaximumSize(QtCore.QSize(118, 16777215))
        self.resetPushButton.setObjectName("resetPushButton")
        self.horizontalLayout_13.addWidget(self.resetPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.savePushButton = QtWidgets.QPushButton(self.frame_15)
        self.savePushButton.setMinimumSize(QtCore.QSize(118, 0))
        self.savePushButton.setMaximumSize(QtCore.QSize(118, 16777215))
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout_13.addWidget(self.savePushButton)
        self.cancelPushButton = QtWidgets.QPushButton(self.frame_15)
        self.cancelPushButton.setMinimumSize(QtCore.QSize(118, 0))
        self.cancelPushButton.setMaximumSize(QtCore.QSize(118, 16777215))
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_13.addWidget(self.cancelPushButton)
        self.verticalLayout_5.addWidget(self.frame_15)
        EditServerWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EditServerWindow)
        QtCore.QMetaObject.connectSlotsByName(EditServerWindow)

    def retranslateUi(self, EditServerWindow):
        _translate = QtCore.QCoreApplication.translate
        EditServerWindow.setWindowTitle(_translate("EditServerWindow", "Edit Server"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.outBoundGroupBox.setTitle(_translate("EditServerWindow", "Outbound"))
        self.protocolLabel.setText(_translate("EditServerWindow", "Protocol"))
        self.protocolComboBox.setItemText(0, _translate("EditServerWindow", "Vmess"))
        self.protocolComboBox.setItemText(1, _translate("EditServerWindow", "Vless"))
        self.protocolComboBox.setItemText(2, _translate("EditServerWindow", "Trojan"))
        self.protocolComboBox.setItemText(3, _translate("EditServerWindow", "Shadowscoks"))
        self.protocolComboBox.setItemText(4, _translate("EditServerWindow", "Socks"))
        self.remakeLabel.setText(_translate("EditServerWindow", "Remake"))
        self.serverGroupBox.setTitle(_translate("EditServerWindow", "Server"))
        self.addressLabel.setText(_translate("EditServerWindow", "Address"))
        self.portLabel.setText(_translate("EditServerWindow", "Port"))
        self.UUIDLabel.setText(_translate("EditServerWindow", "UUID(ID)"))
        self.alterIdLabel.setText(_translate("EditServerWindow", "Alter ID"))
        self.flowLabel.setText(_translate("EditServerWindow", "Flow"))
        self.flowComboBox.setItemText(0, _translate("EditServerWindow", "none"))
        self.securityLabel_2.setText(_translate("EditServerWindow", "Security"))
        self.securityComboBox_2.setItemText(0, _translate("EditServerWindow", "auto"))
        self.securityComboBox_2.setItemText(1, _translate("EditServerWindow", "aes-128-gcm"))
        self.securityComboBox_2.setItemText(2, _translate("EditServerWindow", "chacha20-poly1305"))
        self.securityComboBox_2.setItemText(3, _translate("EditServerWindow", "Chacha20-Poly1305"))
        self.securityComboBox_2.setItemText(4, _translate("EditServerWindow", "none"))
        self.levelLabel.setText(_translate("EditServerWindow", "Level"))
        self.userLabel.setText(_translate("EditServerWindow", "User"))
        self.passwordLabel.setText(_translate("EditServerWindow", "Password"))
        self.methodLabel.setText(_translate("EditServerWindow", "Method"))
        self.methodComboBox.setItemText(0, _translate("EditServerWindow", "aes-256-cfb"))
        self.methodComboBox.setItemText(1, _translate("EditServerWindow", "aes-128-cfb"))
        self.methodComboBox.setItemText(2, _translate("EditServerWindow", "chacha20"))
        self.methodComboBox.setItemText(3, _translate("EditServerWindow", "chacha20-ietf"))
        self.methodComboBox.setItemText(4, _translate("EditServerWindow", "aes-256-gcm"))
        self.methodComboBox.setItemText(5, _translate("EditServerWindow", "aes-128-gcm"))
        self.methodComboBox.setItemText(6, _translate("EditServerWindow", "chacha20-poly1305"))
        self.methodComboBox.setItemText(7, _translate("EditServerWindow", "chacha20-ietf-poly1305"))
        self.otaLabel.setText(_translate("EditServerWindow", "ota"))
        self.otaComboBox.setItemText(0, _translate("EditServerWindow", "true"))
        self.otaComboBox.setItemText(1, _translate("EditServerWindow", "false"))
        self.streamGroupBox.setTitle(_translate("EditServerWindow", "Stream"))
        self.networkLabel.setText(_translate("EditServerWindow", "Network"))
        self.networkComboBox.setItemText(0, _translate("EditServerWindow", "tcp"))
        self.networkComboBox.setItemText(1, _translate("EditServerWindow", "kcp"))
        self.networkComboBox.setItemText(2, _translate("EditServerWindow", "ws"))
        self.networkComboBox.setItemText(3, _translate("EditServerWindow", "http"))
        self.networkComboBox.setItemText(4, _translate("EditServerWindow", "domainsocket"))
        self.networkComboBox.setItemText(5, _translate("EditServerWindow", "quic"))
        self.securityLabel.setText(_translate("EditServerWindow", "Security"))
        self.securityComboBox.setItemText(0, _translate("EditServerWindow", "none"))
        self.securityComboBox.setItemText(1, _translate("EditServerWindow", "tls"))
        self.dsrLabel.setText(_translate("EditServerWindow", "Disable System Root"))
        self.dsrComboBox.setItemText(0, _translate("EditServerWindow", "false"))
        self.dsrComboBox.setItemText(1, _translate("EditServerWindow", "true"))
        self.serverNameLabel.setText(_translate("EditServerWindow", "Server Name"))
        self.allowInsecureLabel.setText(_translate("EditServerWindow", "AllowInsecure"))
        self.allowInsecureComboBox.setItemText(0, _translate("EditServerWindow", "true"))
        self.allowInsecureComboBox.setItemText(1, _translate("EditServerWindow", "false"))
        self.alpnLabel.setText(_translate("EditServerWindow", "Alpn"))
        self.alpnLineEdit.setText(_translate("EditServerWindow", "http/1.1"))
        self.usageLabel.setText(_translate("EditServerWindow", "Usage"))
        self.usageComboBox.setItemText(0, _translate("EditServerWindow", "encipherment"))
        self.usageComboBox.setItemText(1, _translate("EditServerWindow", "verify"))
        self.usageComboBox.setItemText(2, _translate("EditServerWindow", "issue"))
        self.cerLabel.setText(_translate("EditServerWindow", "Certificate"))
        self.cerFilePathLineEdit.setPlaceholderText(_translate("EditServerWindow", "File......"))
        self.chooseCerFilePushButton.setText(_translate("EditServerWindow", "Choose File"))
        self.keyLabel.setText(_translate("EditServerWindow", "Key"))
        self.chooseKeyFileLineEdit.setPlaceholderText(_translate("EditServerWindow", "File......"))
        self.chooseKeyFilePushButton.setText(_translate("EditServerWindow", "Choose File"))
        self.advancedPushButton.setText(_translate("EditServerWindow", "Advanced Settings"))
        self.resetPushButton.setText(_translate("EditServerWindow", "Reset"))
        self.savePushButton.setText(_translate("EditServerWindow", "Save"))
        self.cancelPushButton.setText(_translate("EditServerWindow", "Cancel"))

