# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/import_server_from_url.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportServerFromURLDialog(object):
    def setupUi(self, ImportServerFromURLDialog):
        ImportServerFromURLDialog.setObjectName("ImportServerFromURLDialog")
        ImportServerFromURLDialog.resize(800, 134)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImportServerFromURLDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(ImportServerFromURLDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.urlLabel = QtWidgets.QLabel(self.frame)
        self.urlLabel.setObjectName("urlLabel")
        self.horizontalLayout.addWidget(self.urlLabel)
        self.urlLineEdit = QtWidgets.QLineEdit(self.frame)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.horizontalLayout.addWidget(self.urlLineEdit)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(ImportServerFromURLDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ImportServerFromURLDialog)
        self.buttonBox.accepted.connect(ImportServerFromURLDialog.accept)
        self.buttonBox.rejected.connect(ImportServerFromURLDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ImportServerFromURLDialog)

    def retranslateUi(self, ImportServerFromURLDialog):
        pros = ImportServerFromURLDialog.app.strings.properties
        _translate = QtCore.QCoreApplication.translate
        ImportServerFromURLDialog.setWindowTitle(_translate("ImportServerFromURLDialog", pros['importServerFromUrl']))
        self.urlLabel.setText(_translate("ImportServerFromURLDialog", pros['serverUrl']))
