# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/qrcode.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QRCodeMainWindow(object):
    def setupUi(self, QRCodeMainWindow):
        QRCodeMainWindow.setObjectName("QRCodeMainWindow")
        QRCodeMainWindow.resize(502, 436)
        self.centralwidget = QtWidgets.QWidget(QRCodeMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.qrcodeLabel = QtWidgets.QLabel(self.frame)
        self.qrcodeLabel.setText("")
        self.qrcodeLabel.setPixmap(QtGui.QPixmap(":/newPrefix/baseline_qr_code_2_black_18dp.png"))
        self.qrcodeLabel.setObjectName("qrcodeLabel")
        self.horizontalLayout.addWidget(self.qrcodeLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.urLabel = QtWidgets.QLabel(self.centralwidget)
        self.urLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.urLabel.setWordWrap(True)
        self.urLabel.setObjectName("urLabel")
        self.verticalLayout.addWidget(self.urLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        QRCodeMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(QRCodeMainWindow)
        QtCore.QMetaObject.connectSlotsByName(QRCodeMainWindow)

    def retranslateUi(self, QRCodeMainWindow):
        pros = QRCodeMainWindow.app.strings.properties
        _translate = QtCore.QCoreApplication.translate
        QRCodeMainWindow.setWindowTitle(_translate("QRCodeMainWindow", pros['showServerQRCode']))
        self.label.setText(_translate("QRCodeMainWindow", "servername"))
        self.urLabel.setText(_translate("QRCodeMainWindow", "url"))

